version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app/python-docker  # Monta el directorio actual en el contenedor
    working_dir: /app/python-docker
    command: uvicorn fastapi_app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Cargar la API key desde un .env